### ISSUE TITLE
CMUnit not displaying FCE hours on SIO

### ISSUE THREAD

**Issue by alex-stanescu** [cmu-student-government/cmunit#10]
CMUnit extension is not displaying FCE hours on SIO right now. Proof attached

![image](https://user-images.githubusercontent.com/16586614/47273294-32c2bd00-d560-11e8-9e8f-559d5ee27a3f.png)

**Comment by omarsinan** [comment]
Until they fix the issue, I am using https://cmu-student-government.github.io/cmunit/fce.json to get info about the FCE hours.

**Comment by user2589** [comment]
the Registrar's Office changed some of SIO internals, so CMUnits couldn't find where to FCE hours.
I implemented a fix to keep up with these changes and uploaded to Chrome store (version 0.0.1.3). 
The review process takes about an hour, so it should be publicly available pretty soon.

Can you try and see if it works?

**Comment by cmax4jam** [comment]
The extension now shows FCE hours next to course titles as desired but does not add up hours correctly for total FCE. Mine shows well over 100 when it should say around 50 something if added correctly.

**Comment by user2589** [comment]
@cmax4jam I can't reproduce. Can you list course numbers?

**Comment by cmax4jam** [comment]
Sure, here's a screenshot.  
![screen shot 2018-10-29 at 10 08 03 pm](https://user-images.githubusercontent.com/7969362/47691118-26290f00-dbc7-11e8-8004-b39e7789e8a3.png)

**Comment by user2589** [comment]
ok, I found another bug. I uploaded a new version, 0.0.1.4. Can you please check again once it is available?

**Comment by cmax4jam** [comment]
Yes, I'll check as soon as it's up.  Thanks for the quick response!

**Comment by cmax4jam** [comment]
Works great now.  Thanks @user2589 for the quick fix!
