### ISSUE TITLE
Extension pulls data from summer

### ISSUE THREAD

**Issue by maximusjohnsonus** [cmu-student-government/cmunit#4]
E.g. for 15150 it reports 21.3 hours, which is the data from last summer. This is very misleading as classes take significantly more time over the summer than they do during the year.

**Comment by user2589** [comment]
@maximusjohnsonus this question was explored in issue #3 and essentially no difference was found. I will recheck this specific course and get with more data tomorrow.

**Comment by user2589** [comment]
I confirm the issue. The comparison in #3 code was incorrect.
The fix is already deployed. Since it was on the data side, it does not require an extension update.
